Make scripts more robust and flexible (#75)
* Make scripts more robust and flexible

* Update README.md

diff --git a/script/build b/script/build
--- a/script/build
+++ b/script/build
@@ -6,8 +6,12 @@
 ###############################################################################
 # Build cpu.
 
-set -o errexit
-
+if [ "$0" = "$BASH_SOURCE" ]
+then
+  set -o errexit
+else
+  echo "Warning: This script should not be sourced. Skipping exit on error."
+fi
 
 SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]:-$0}")" >/dev/null 2>&1 ; pwd -P )"
 
@@ -16,6 +20,14 @@ SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]:-$0}")" >/dev/null 2>&1 ; pwd -P 
     --name build \
     --desc "Build cpu." \
     -- "$@"
+
+###############################################################################
+# Globals
+if [ -z "${VPL_CPU_BUILD_DIR}" ]
+then
+  VPL_CPU_BUILD_DIR="${PROJ_DIR}/_build"
+fi
+###############################################################################
 
 if [ -n "${BOOTSTRAP_OPT}" ]
 then
@@ -31,23 +43,21 @@ fi
 
 COFIG_CM_OPT="-DCMAKE_BUILD_TYPE=${COFIG_OPT}"
 
-pushd "${PROJ_DIR}"
-  BUILD_DIR=_build
-  if [ "${GPL_OPT}" == "yes" ]; then
-    CMAKE_GPL_OPT=-DBUILD_GPL_X264=ON
-  fi
-  if [ "${WARNING_AS_ERROR_OPT}" == "yes" ]; then
-    CMAKE_WARN_OPTS=-DENABLE_WARNING_AS_ERROR=ON
-  fi
-  mkdir -p ${BUILD_DIR}
-  pushd "${BUILD_DIR}"
-    cmake "${INSTALL_PREFIX_CM_OPT}" ${CMAKE_GPL_OPT} ${CMAKE_WARN_OPTS} "${COFIG_CM_OPT}" ..
-    make -j "$(nproc)" VERBOSE=1
-    cmake --build . --config "${COFIG_OPT}" --target package
-  popd
+BUILD_DIR="${VPL_CPU_BUILD_DIR}"
+if [ "${GPL_OPT}" == "yes" ]; then
+  CMAKE_GPL_OPT=-DBUILD_GPL_X264=ON
+fi
+if [ "${WARNING_AS_ERROR_OPT}" == "yes" ]; then
+  CMAKE_WARN_OPTS=-DENABLE_WARNING_AS_ERROR=ON
+fi
+mkdir -p ${BUILD_DIR}
+pushd "${BUILD_DIR}"
+  cmake "${INSTALL_PREFIX_CM_OPT}" ${CMAKE_GPL_OPT} ${CMAKE_WARN_OPTS} "${COFIG_CM_OPT}" "${PROJ_DIR}"
+  make -j "$(nproc)" VERBOSE=1
+  cmake --build . --config "${COFIG_OPT}" --target package
 popd
 
 # Signal to CI system
 if [ -n "${TEAMCITY_VERSION}" ]; then
-  echo "##teamcity[publishArtifacts 'oneVPL-cpu/${BUILD_DIR}/*-all.zip=>']"
+  echo "##teamcity[publishArtifacts '${BUILD_DIR}/*-all.zip=>']"
 fi
diff --git a/script/clean b/script/clean
--- a/script/clean
+++ b/script/clean
@@ -6,7 +6,12 @@
 ###############################################################################
 # Clean cpu.
 
-set -o errexit
+if [ "$0" = "$BASH_SOURCE" ]
+then
+  set -o errexit
+else
+  echo "Warning: This script should not be sourced. Skipping exit on error."
+fi
 
 
 SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]:-$0}")" >/dev/null 2>&1 ; pwd -P )"
@@ -17,6 +22,25 @@ SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]:-$0}")" >/dev/null 2>&1 ; pwd -P 
     --desc "Clean cpu." \
     -- "$@"
 
+###############################################################################
+# Globals
+if [ -z "${VPL_CPU_DEPS_BUILD_DIR}" ]
+then
+  VPL_CPU_DEPS_BUILD_DIR="${PROJ_DIR}/_extbuild"
+fi
+
+if [ -z "${VPL_BUILD_DEPENDENCIES}" ]
+then
+  VPL_BUILD_DEPENDENCIES="${PROJ_DIR}/_deps"
+fi
+
+if [ -z "${VPL_CPU_BUILD_DIR}" ]
+then
+  VPL_CPU_BUILD_DIR="${PROJ_DIR}/_build"
+fi
+###############################################################################
+
+
 if [ -n "${BOOTSTRAP_OPT}" ]
 then
   if [ -e "${VPL_BUILD_DEPENDENCIES}" ]
@@ -24,22 +48,15 @@ then
       echo "Cleaning dependencies cache folder..."
       rm -rf "${VPL_BUILD_DEPENDENCIES}"
   fi
+  if [ -e "${VPL_CPU_DEPS_BUILD_DIR}" ]
+  then
+      echo "Cleaning dependencies build folder..."
+      rm -rf "${VPL_CPU_DEPS_BUILD_DIR}"
+  fi
 fi
 
-pushd "${PROJ_DIR}"
-  if [ -e _deps ]
-  then
-      echo "Cleaning cpu dependencies folder..."
-      rm -rf _deps
-  fi
-  if [ -e _extbuild ]
-  then
-      echo "Cleaning cpu dependencies build folder..."
-      rm -rf _extbuild
-  fi
-  if [ -e _build ]
-  then
-      echo "Cleaning cpu build folder..."
-      rm -rf _build
-  fi
-popd
+if [ -e "${VPL_CPU_BUILD_DIR}" ]
+then
+    echo "Cleaning cpu build folder..."
+    rm -rf "${VPL_CPU_BUILD_DIR}"
+fi
diff --git a/script/install b/script/install
--- a/script/install
+++ b/script/install
@@ -6,7 +6,12 @@
 ###############################################################################
 # Install cpu.
 
-set -o errexit
+if [ "$0" = "$BASH_SOURCE" ]
+then
+  set -o errexit
+else
+  echo "Warning: This script should not be sourced. Skipping exit on error."
+fi
 
 
 SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]:-$0}")" >/dev/null 2>&1 ; pwd -P )"
@@ -17,7 +22,13 @@ SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]:-$0}")" >/dev/null 2>&1 ; pwd -P 
     --desc "Install cpu." \
     -- "$@"
 
-pushd "${PROJ_DIR}"
-    BUILD_DIR=_build
-    cmake --build "${BUILD_DIR}" --config "${COFIG_OPT}" --target install
-popd
+###############################################################################
+# Globals
+if [ -z "${VPL_CPU_BUILD_DIR}" ]
+then
+  VPL_CPU_BUILD_DIR="${PROJ_DIR}/_build"
+fi
+###############################################################################
+
+BUILD_DIR="${VPL_CPU_BUILD_DIR}"
+cmake --build "${BUILD_DIR}" --config "${COFIG_OPT}" --target install
diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -6,8 +6,12 @@
 ###############################################################################
 # Run basic tests on base.
 
-set -o errexit
-
+if [ "$0" = "$BASH_SOURCE" ]
+then
+  set -o errexit
+else
+  echo "Warning: This script should not be sourced. Skipping exit on error."
+fi
 
 SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]:-$0}")" >/dev/null 2>&1 ; pwd -P )"
 
@@ -16,6 +20,14 @@ SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]:-$0}")" >/dev/null 2>&1 ; pwd -P 
     --name test \
     --desc "Run basic tests on base." \
     -- "$@"
+
+###############################################################################
+# Globals
+if [ -z "${VPL_CPU_BUILD_DIR}" ]
+then
+  VPL_CPU_BUILD_DIR="${PROJ_DIR}/_build"
+fi
+###############################################################################
 
 result_all=0
 
@@ -40,24 +52,22 @@ fi
 
 result_all=0
 
-pushd "${PROJ_DIR}"
-  . test/tools/env/vars.sh
-  export ffmpeg_dir="${VPL_BUILD_DEPENDENCIES}/bin"
-  export PATH=${ffmpeg_dir}:${PATH}
+. ${PROJ_DIR}/test/tools/env/vars.sh
+export ffmpeg_dir="${VPL_BUILD_DEPENDENCIES}/bin"
+export PATH=${ffmpeg_dir}:${PATH}
 
-  BUILD_DIR=_build
-  pushd "${BUILD_DIR}"
-    export LD_LIBRARY_PATH=${PWD}:${LD_LIBRARY_PATH}
-    echo "--- Running Unit Tests ---"
-    # using " || ret=$?" to allow fail and capture exit code with errexit set
-    ./vpl-utest "--gtest_output=xml:${PROJ_DIR}/_logs/" || ret=$?
-    if [ ${ret} -ne 0 ]; then
-        echo "--- Unit Tests FAILED ---"
-        (( result_all++ )) || true
-    else
-        echo "--- Unit Tests PASSED ---"
-    fi
-  popd
+BUILD_DIR="${VPL_CPU_BUILD_DIR}"
+pushd "${BUILD_DIR}"
+  export LD_LIBRARY_PATH=${PWD}:${LD_LIBRARY_PATH}
+  echo "--- Running Unit Tests ---"
+  # using " || ret=$?" to allow fail and capture exit code with errexit set
+  ./vpl-utest "--gtest_output=xml:${PROJ_DIR}/_logs/" || ret=$?
+  if [ ${ret} -ne 0 ]; then
+      echo "--- Unit Tests FAILED ---"
+      (( result_all++ )) || true
+  else
+      echo "--- Unit Tests PASSED ---"
+  fi
 popd
 
 exit "${result_all}"
