Remove fails blocking remaining CI test

diff --git a/script/cibuild b/script/cibuild
--- a/script/cibuild
+++ b/script/cibuild
@@ -8,18 +8,45 @@
 script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 proj_dir="$( dirname "${script_dir}" )"
 cd ${proj_dir}
-set -o errexit
+##set -o errexit
 ## start of commands -----------------------------------------------------------
+## capture ci errors that should not block the rest of the chain
+ci_error=0
+
 source test/tools/env/vars.sh
 script/lint
+if [ $? -ne 0 ];then
+    echo "--- Linting FAILED ---"
+    ci_error=1
+fi
+
 if [ -z "$VPL_BUILD_DEPENDENCIES" ];then
     source script/bootstrap
+    if [ $? -ne 0 ];then
+        echo "--- Bootstrapping FAILED---"
+        exit 1
+    fi
 fi
 script/package
+if [ $? -ne 0 ];then
+    echo "--- Packaging FAILED---"
+    exit 1
+fi
 
 # run smoke tests
 pushd _build
 ${proj_dir}/script/test
+if [ $? -ne 0 ];then
+    echo "--- Smoke Tests FAILED ---"
+    ci_error=1
+fi
 popd
-echo --- All Smoke Tests PASSED ---
+
+if [ $ci_error -ne 0 ]; then
+    echo "--- CI testing FAILED ---"
+    exit 1
+else
+    echo "---All Tests PASSED ---"
+    exit 0
+fi
 
